Module4 task1
htmlacademy-javascript/1789463-kekstagram-25 pull request #3
Opened 2022-03-14 18:23 UTC by MaxMad446

2022-03-15 06:36 UTC, Dima-Dim requested changes

2022-03-15 06:36 UTC, Dima-Dim commented on js/main.js
> +createDescriptionPhoto();
Функция reateDescriptionPhoto принимает один аргумент, а ты, вызывая её ничего не передаёшь. В итоге в получаемом объекте id будет undefined.

2022-03-15 06:36 UTC, Dima-Dim commented on js/main.js
> +    comments:[createComments(),createComments()],
При таком подходе тут будет всегда 2 комментария. Но заданию это не противоречит, так что, наверное, можно оставить и так.

2022-03-15 06:36 UTC, Dima-Dim commented on js/main.js
> +    id: getRandomNum(1, 25),
"id — случайное число. Идентификаторы не должны повторяться." - тут нет гарантий что он не повториться.

2022-03-15 06:36 UTC, Dima-Dim commented on js/main.js
> +    id: index,
"id, число — идентификатор описания. Это число от 1 до 25. Идентификаторы не должны повторяться."

2022-03-15 08:35 UTC, MaxMad446 commented on js/main.js
> +    comments:[createComments(),createComments()],
а как лучше?

2022-03-15 14:19 UTC, Dima-Dim commented on js/main.js
> +    comments:[createComments(),createComments()],
Лучше для каждой фото генерировать разное количество комментариев.

2022-03-18 07:15 UTC, Dima-Dim reviewed
Когда будешь отправлять на проверку следующее заданий, опубликуй его и проверь что оно нормально работает.

2022-03-18 07:15 UTC, merged