Модуляция
htmlacademy-javascript/1789463-kekstagram-25 pull request #4
Opened 2022-03-18 12:18 UTC by MaxMad446

2022-03-19 04:31 UTC, Dima-Dim requested changes
https://htmlacademy-javascript.github.io/1789463-kekstagram-25/4/
Всё ещё `GET https://htmlacademy-javascript.github.io/js/main.js net::ERR_ABORTED 404` в консоле.

2022-03-20 07:10 UTC, Dima-Dim commented
Внесённые правки не решали проблему описанную ранее. Всё ещё
https://htmlacademy-javascript.github.io/1789463-kekstagram-25/4/
GET https://htmlacademy-javascript.github.io/js/main.js net::ERR_ABORTED 404 в консоле.

2022-03-24 06:41 UTC, Dima-Dim commented on js/photo.js
> +window.console.log(getPictures);
Можно просто `console.log(getPictures);`

2022-03-24 06:41 UTC, merged

2022-03-24 09:10 UTC, MaxMad446 commented on js/photo.js
> +window.console.log(getPictures);
тогда он красным подсвечивает

2022-03-24 12:51 UTC, Dima-Dim commented on js/photo.js
> +window.console.log(getPictures);
Значит это локальный лайф хак по обходу линтера :)